In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd

In [3]:
from marine_qc import (
    flag_duplicates,
    get_duplicates,
    remove_duplicates,
)

In [4]:
from data import get_advanced_data

# How to use the duplicate checker to detect possibly duplicated observations

We need some text!!!

In [5]:
data = get_advanced_data()
data

  station_id    lon    lat                date      vsi    dsi    sst
A         AA  22.30  71.30 2022-02-01 00:00:00  0.00000    0.0  300.0
B         AA  29.70  71.30 2022-02-01 00:00:00  4.11552  315.0  302.0
C         AA  32.00  71.20 2022-02-01 00:00:00      NaN    NaN  300.0
D         AA   8.10  66.00 2022-02-01 00:00:00  0.00000    0.0  300.0
E         AA -21.20  65.80 2022-02-01 00:00:00  0.00000    0.0  300.0
F         AA -21.20  65.80 2022-02-01 00:00:00  0.00000    0.0  300.0
G         AA  21.20 -65.80 2022-02-01 00:00:00  0.00000    0.0  300.0
H         AA  29.70  71.30 2022-02-01 00:01:00  4.11552  315.0  300.0
I         AA  29.70  71.30 2022-02-02 00:00:00  4.11552  315.0  300.0
J         AA  32.00  71.20 2022-02-01 00:00:00      NaN    NaN  300.0
K         AA   8.50  66.00 2022-02-01 00:00:00  0.00000    0.0  300.0
L         AA   8.15  66.05 2022-02-01 00:00:00  0.00000    0.0  300.0
M         AB   8.10  66.00 2022-02-01 00:00:00  0.00000    0.0  300.0
N         AA   8.05  65.95 2022-02-01 00:00:00  0.00000    0.0  300.0
O         BB   8.10  66.00 2022-02-01 00:00:00  0.00000    0.0  300.0
P         AA -21.40  65.60 2022-02-01 00:00:00  0.00000    0.0  300.0
Q         AA -21.10  65.90 2022-02-01 00:00:00  0.00000    0.0  300.0
R         AA  29.70  71.30 2022-02-01 00:00:00  4.11552  316.0  300.0
S         AA  29.70  71.30 2022-02-01 00:00:00  4.00000  315.0  300.0
T         AA  29.70  71.30 2022-02-01 00:00:00  4.11552    NaN  300.0
U         AA  29.70  71.30 2022-02-01 00:00:00      NaN  315.0  300.0

In [6]:
get_duplicates(
    data=data,
)

INFO:splink.internals.linker_components.inference:Blocking time: 0.00 seconds
INFO:splink.internals.linker_components.inference:Predict time: 0.10 seconds
WARNING:splink.internals.linker:
 -- WARNING --
You have called predict(), but there are some parameter estimates which have neither been estimated or specified in your settings dictionary.  To produce predictions the following untrained trained parameters will use default values.
Comparison: 'station_id':
    m values not fully trained
Comparison: 'station_id':
    u values not fully trained
Comparison: 'lon':
    m values not fully trained
Comparison: 'lon':
    u values not fully trained
Comparison: 'lat':
    m values not fully trained
Comparison: 'lat':
    u values not fully trained
Comparison: 'date':
    m values not fully trained
Comparison: 'date':
    u values not fully trained
Comparison: 'vsi':
    m values not fully trained
Comparison: 'vsi':
    u values not fully trained
Comparison: 'dsi':
    m values not fully trained
Comparison: 'dsi':
    u values not fully trained

A       NaN
B         H
C         J
D    [L, N]
E    [F, Q]
F         E
G       NaN
H         B
I       NaN
J         C
K       NaN
L         D
M       NaN
N         D
O       NaN
P       NaN
Q         E
R       NaN
S       NaN
T       NaN
U       NaN
Name: duplicates, dtype: object

In [7]:
get_duplicates(
    data=data,
    ignore_entries={"station_id": ["AA", "BB"]},
)

INFO:splink.internals.linker_components.inference:Blocking time: 0.00 seconds
INFO:splink.internals.linker_components.inference:Predict time: 0.11 seconds
WARNING:splink.internals.linker:
 -- WARNING --
You have called predict(), but there are some parameter estimates which have neither been estimated or specified in your settings dictionary.  To produce predictions the following untrained trained parameters will use default values.
Comparison: 'station_id':
    m values not fully trained
Comparison: 'station_id':
    u values not fully trained
Comparison: 'lon':
    m values not fully trained
Comparison: 'lon':
    u values not fully trained
Comparison: 'lat':
    m values not fully trained
Comparison: 'lat':
    u values not fully trained
Comparison: 'date':
    m values not fully trained
Comparison: 'date':
    u values not fully trained
Comparison: 'vsi':
    m values not fully trained
Comparison: 'vsi':
    u values not fully trained
Comparison: 'dsi':
    m values not fully trained
Comparison: 'dsi':
    u values not fully trained

A             NaN
B               H
C               J
D    [L, M, N, O]
E          [F, Q]
F               E
G             NaN
H               B
I             NaN
J               C
K             NaN
L               D
M               D
N               D
O               D
P             NaN
Q               E
R             NaN
S             NaN
T             NaN
U             NaN
Name: duplicates, dtype: object

In [8]:
get_duplicates(
    data=data,
    ignore_nan_both="vsi",
)

INFO:splink.internals.linker_components.inference:Blocking time: 0.00 seconds
INFO:splink.internals.linker_components.inference:Predict time: 0.09 seconds
WARNING:splink.internals.linker:
 -- WARNING --
You have called predict(), but there are some parameter estimates which have neither been estimated or specified in your settings dictionary.  To produce predictions the following untrained trained parameters will use default values.
Comparison: 'station_id':
    m values not fully trained
Comparison: 'station_id':
    u values not fully trained
Comparison: 'lon':
    m values not fully trained
Comparison: 'lon':
    u values not fully trained
Comparison: 'lat':
    m values not fully trained
Comparison: 'lat':
    u values not fully trained
Comparison: 'date':
    m values not fully trained
Comparison: 'date':
    u values not fully trained
Comparison: 'vsi':
    m values not fully trained
Comparison: 'vsi':
    u values not fully trained
Comparison: 'dsi':
    m values not fully trained
Comparison: 'dsi':
    u values not fully trained

A       NaN
B         H
C       NaN
D    [L, N]
E    [F, Q]
F         E
G       NaN
H         B
I       NaN
J       NaN
K       NaN
L         D
M       NaN
N         D
O       NaN
P       NaN
Q         E
R       NaN
S       NaN
T       NaN
U       NaN
Name: duplicates, dtype: object

In [9]:
get_duplicates(
    data=data,
    ignore_nan_either="vsi",
)

INFO:splink.internals.linker_components.inference:Blocking time: 0.00 seconds
INFO:splink.internals.linker_components.inference:Predict time: 0.10 seconds
WARNING:splink.internals.linker:
 -- WARNING --
You have called predict(), but there are some parameter estimates which have neither been estimated or specified in your settings dictionary.  To produce predictions the following untrained trained parameters will use default values.
Comparison: 'station_id':
    m values not fully trained
Comparison: 'station_id':
    u values not fully trained
Comparison: 'lon':
    m values not fully trained
Comparison: 'lon':
    u values not fully trained
Comparison: 'lat':
    m values not fully trained
Comparison: 'lat':
    u values not fully trained
Comparison: 'date':
    m values not fully trained
Comparison: 'date':
    u values not fully trained
Comparison: 'vsi':
    m values not fully trained
Comparison: 'vsi':
    u values not fully trained
Comparison: 'dsi':
    m values not fully trained
Comparison: 'dsi':
    u values not fully trained

A          NaN
B    [H, U, S]
C            J
D       [L, N]
E       [F, Q]
F            E
G          NaN
H            B
I          NaN
J            C
K          NaN
L            D
M          NaN
N            D
O          NaN
P          NaN
Q            E
R          NaN
S            B
T          NaN
U            B
Name: duplicates, dtype: object

In [10]:
get_duplicates(
    data=data,
    ignore_columns="station_id",
)

INFO:splink.internals.linker_components.inference:Blocking time: 0.00 seconds
INFO:splink.internals.linker_components.inference:Predict time: 0.09 seconds
WARNING:splink.internals.linker:
 -- WARNING --
You have called predict(), but there are some parameter estimates which have neither been estimated or specified in your settings dictionary.  To produce predictions the following untrained trained parameters will use default values.
Comparison: 'lon':
    m values not fully trained
Comparison: 'lon':
    u values not fully trained
Comparison: 'lat':
    m values not fully trained
Comparison: 'lat':
    u values not fully trained
Comparison: 'date':
    m values not fully trained
Comparison: 'date':
    u values not fully trained
Comparison: 'vsi':
    m values not fully trained
Comparison: 'vsi':
    u values not fully trained
Comparison: 'dsi':
    m values not fully trained
Comparison: 'dsi':
    u values not fully trained

A             NaN
B               H
C               J
D    [L, M, N, O]
E          [F, Q]
F               E
G             NaN
H               B
I             NaN
J               C
K             NaN
L               D
M               D
N               D
O               D
P             NaN
Q               E
R             NaN
S             NaN
T             NaN
U             NaN
Name: duplicates, dtype: object

In [11]:
get_duplicates(
    data=data,
    offsets={"lat": 1.0, "lon": 1.0, "date": 360},
)

INFO:splink.internals.linker_components.inference:Blocking time: 0.00 seconds
INFO:splink.internals.linker_components.inference:Predict time: 0.10 seconds
WARNING:splink.internals.linker:
 -- WARNING --
You have called predict(), but there are some parameter estimates which have neither been estimated or specified in your settings dictionary.  To produce predictions the following untrained trained parameters will use default values.
Comparison: 'station_id':
    m values not fully trained
Comparison: 'station_id':
    u values not fully trained
Comparison: 'lon':
    m values not fully trained
Comparison: 'lon':
    u values not fully trained
Comparison: 'lat':
    m values not fully trained
Comparison: 'lat':
    u values not fully trained
Comparison: 'date':
    m values not fully trained
Comparison: 'date':
    u values not fully trained
Comparison: 'vsi':
    m values not fully trained
Comparison: 'vsi':
    u values not fully trained
Comparison: 'dsi':
    m values not fully trained
Comparison: 'dsi':
    u values not fully trained

A          NaN
B            H
C            J
D    [K, L, N]
E    [F, P, Q]
F            E
G          NaN
H            B
I          NaN
J            C
K            D
L            D
M          NaN
N            D
O          NaN
P            E
Q            E
R          NaN
S          NaN
T          NaN
U          NaN
Name: duplicates, dtype: object

In [12]:
get_duplicates(
    data=data,
    compare_level_libraries={"sst": "AbsoluteDifferenceLevel"},
    offsets={"sst": 1.0},
)

INFO:splink.internals.linker_components.inference:Blocking time: 0.00 seconds
INFO:splink.internals.linker_components.inference:Predict time: 0.12 seconds
WARNING:splink.internals.linker:
 -- WARNING --
You have called predict(), but there are some parameter estimates which have neither been estimated or specified in your settings dictionary.  To produce predictions the following untrained trained parameters will use default values.
Comparison: 'station_id':
    m values not fully trained
Comparison: 'station_id':
    u values not fully trained
Comparison: 'lon':
    m values not fully trained
Comparison: 'lon':
    u values not fully trained
Comparison: 'lat':
    m values not fully trained
Comparison: 'lat':
    u values not fully trained
Comparison: 'date':
    m values not fully trained
Comparison: 'date':
    u values not fully trained
Comparison: 'vsi':
    m values not fully trained
Comparison: 'vsi':
    u values not fully trained
Comparison: 'dsi':
    m values not fully trained
Comparison: 'dsi':
    u values not fully trained
Comparison: 'sst':
    m values not fully trained
Comparison: 'sst':
    u values not fully trained

A       NaN
B       NaN
C         J
D    [L, N]
E    [F, Q]
F         E
G       NaN
H       NaN
I       NaN
J         C
K       NaN
L         D
M       NaN
N         D
O       NaN
P       NaN
Q         E
R       NaN
S       NaN
T       NaN
U       NaN
Name: duplicates, dtype: object

In [13]:
flag_duplicates(
    data=data,
)

INFO:splink.internals.linker_components.inference:Blocking time: 0.00 seconds
INFO:splink.internals.linker_components.inference:Predict time: 0.11 seconds
WARNING:splink.internals.linker:
 -- WARNING --
You have called predict(), but there are some parameter estimates which have neither been estimated or specified in your settings dictionary.  To produce predictions the following untrained trained parameters will use default values.
Comparison: 'station_id':
    m values not fully trained
Comparison: 'station_id':
    u values not fully trained
Comparison: 'lon':
    m values not fully trained
Comparison: 'lon':
    u values not fully trained
Comparison: 'lat':
    m values not fully trained
Comparison: 'lat':
    u values not fully trained
Comparison: 'date':
    m values not fully trained
Comparison: 'date':
    u values not fully trained
Comparison: 'vsi':
    m values not fully trained
Comparison: 'vsi':
    u values not fully trained
Comparison: 'dsi':
    m values not fully trained
Comparison: 'dsi':
    u values not fully trained

A    0
B    1
C    1
D    1
E    1
F    3
G    0
H    3
I    0
J    3
K    0
L    3
M    0
N    3
O    0
P    0
Q    3
R    0
S    0
T    0
U    0
Name: duplicate_flags, dtype: int64

In [14]:
results = remove_duplicates(
    data=data,
)
pd.DataFrame(results).T

INFO:splink.internals.linker_components.inference:Blocking time: 0.00 seconds
INFO:splink.internals.linker_components.inference:Predict time: 0.12 seconds
WARNING:splink.internals.linker:
 -- WARNING --
You have called predict(), but there are some parameter estimates which have neither been estimated or specified in your settings dictionary.  To produce predictions the following untrained trained parameters will use default values.
Comparison: 'station_id':
    m values not fully trained
Comparison: 'station_id':
    u values not fully trained
Comparison: 'lon':
    m values not fully trained
Comparison: 'lon':
    u values not fully trained
Comparison: 'lat':
    m values not fully trained
Comparison: 'lat':
    u values not fully trained
Comparison: 'date':
    m values not fully trained
Comparison: 'date':
    u values not fully trained
Comparison: 'vsi':
    m values not fully trained
Comparison: 'vsi':
    u values not fully trained
Comparison: 'dsi':
    m values not fully trained
Comparison: 'dsi':
    u values not fully trained

  station_id   lon   lat                 date      vsi    dsi    sst
A         AA  22.3  71.3  2022-02-01 00:00:00      0.0    0.0  300.0
B         AA  29.7  71.3  2022-02-01 00:00:00  4.11552  315.0  302.0
C         AA  32.0  71.2  2022-02-01 00:00:00      NaN    NaN  300.0
D         AA   8.1  66.0  2022-02-01 00:00:00      0.0    0.0  300.0
E         AA -21.2  65.8  2022-02-01 00:00:00      0.0    0.0  300.0
G         AA  21.2 -65.8  2022-02-01 00:00:00      0.0    0.0  300.0
I         AA  29.7  71.3  2022-02-02 00:00:00  4.11552  315.0  300.0
K         AA   8.5  66.0  2022-02-01 00:00:00      0.0    0.0  300.0
M         AB   8.1  66.0  2022-02-01 00:00:00      0.0    0.0  300.0
O         BB   8.1  66.0  2022-02-01 00:00:00      0.0    0.0  300.0
P         AA -21.4  65.6  2022-02-01 00:00:00      0.0    0.0  300.0
R         AA  29.7  71.3  2022-02-01 00:00:00  4.11552  316.0  300.0
S         AA  29.7  71.3  2022-02-01 00:00:00      4.0  315.0  300.0
T         AA  29.7  71.3  2022-02-01 00:00:00  4.11552    NaN  300.0
U         AA  29.7  71.3  2022-02-01 00:00:00      NaN  315.0  300.0