In [1]:
%load_ext autoreload
%autoreload 2

In [15]:
import matplotlib.pyplot as plt

from marine_qc import (
    do_iquam_track_check,
    do_multiple_sequential_check,
    do_spike_check,
    do_track_check,
)

In [3]:
from examples.data import get_sequential_data

C:\Users\llierham\mobaxterm\.venvs\mp_py\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# How to use quality control checks with sequential reports

We need some text!!!

In [13]:
data = get_sequential_data()
data

,buoy_id,date,lat,lon,sst,vsi,dsi
0,drifter_001,2026-07-01 00:00:00,44.995953,-29.988554,20.251012,0.900000,120.000000
1,drifter_001,2026-07-01 01:00:00,44.990586,-29.976159,20.355881,0.974540,127.764571
2,drifter_001,2026-07-01 02:00:00,44.983947,-29.962881,20.454013,1.044000,135.000000
3,drifter_001,2026-07-01 03:00:00,44.976210,-29.948845,20.538790,1.103647,141.213203
4,drifter_001,2026-07-01 04:00:00,44.967642,-29.934226,20.604500,1.149415,145.980762
5,drifter_001,2026-07-01 05:00:00,44.958562,-29.919241,20.646730,1.178187,148.977775
6,drifter_001,2026-07-01 06:00:00,44.949310,-29.904132,20.662673,1.188000,150.000000
7,drifter_001,2026-07-01 07:00:00,44.940229,-29.889147,20.651313,1.178187,148.977775
8,drifter_001,2026-07-01 08:00:00,44.931662,-29.874529,20.613495,1.149415,145.980762
9,drifter_001,2026-07-01 09:00:00,44.923925,-29.860492,20.551861,1.103647,141.213203
10,drifter_001,2026-07-01 10:00:00,44.917286,-29.847214,20.470678,1.044000,135.000000
11,drifter_001,2026-07-01 11:00:00,44.911919,-29.834820,20.375548,0.974540,127.764571
12,drifter_001,2026-07-01 12:00:00,44.907872,-29.823373,20.273032,0.900000,120.000000
13,drifter_001,2026-07-01 13:00:00,44.905063,-29.812875,20.170207,0.825460,112.235429
14,drifter_001,2026-07-01 14:00:00,44.903303,-29.803260,20.074174,0.756000,105.000000
15,drifter_001,2026-07-01 15:00:00,44.902346,-29.794403,19.991571,0.696353,98.786797
16,drifter_001,2026-07-01 16:00:00,44.901936,-29.786129,19.928106,0.650585,94.019238
17,drifter_001,2026-07-01 17:00:00,44.901836,-29.778220,19.888171,0.621813,91.022225
18,drifter_001,2026-07-01 18:00:00,44.901836,-29.770437,19.874541,0.612000,90.000000
19,drifter_001,2026-07-01 19:00:00,44.901737,-29.762528,19.888196,0.621813,91.022225
20,drifter_001,2026-07-01 20:00:00,44.901327,-29.754254,19.928258,0.650585,94.019238
21,drifter_001,2026-07-01 21:00:00,44.900370,-29.745398,19.992065,0.696353,98.786797
22,drifter_001,2026-07-01 22:00:00,44.898610,-29.735783,20.075347,0.756000,105.000000
23,drifter_001,2026-07-01 23:00:00,44.895801,-29.725284,20.172522,0.825460,112.235429
24,drifter_001,2026-07-02 00:00:00,44.891754,-29.713838,20.277061,0.900000,120.000000
25,drifter_001,2026-07-02 01:00:00,44.886387,-29.701443,20.381931,0.974540,127.764571
26,drifter_001,2026-07-02 02:00:00,44.879748,-29.688165,20.480063,1.044000,135.000000
27,drifter_001,2026-07-02 03:00:00,44.872011,-29.674129,20.564840,1.103647,141.213203
28,drifter_001,2026-07-02 04:00:00,44.863443,-29.659510,20.630549,1.149415,145.980762
29,drifter_001,2026-07-02 05:00:00,44.854363,-29.644525,20.672780,1.178187,148.977775
30,drifter_001,2026-07-02 06:00:00,44.845111,-29.629416,20.688722,1.188000,150.000000
31,drifter_001,2026-07-02 07:00:00,44.836030,-29.614431,20.677363,1.178187,148.977775
32,drifter_001,2026-07-02 08:00:00,44.827463,-29.599813,20.639544,1.149415,145.980762
33,drifter_001,2026-07-02 09:00:00,44.819726,-29.585776,20.577911,1.103647,141.213203
34,drifter_001,2026-07-02 10:00:00,44.813087,-29.572498,20.496728,1.044000,135.000000
35,drifter_001,2026-07-02 11:00:00,44.807720,-29.560104,20.401598,0.974540,127.764571
36,drifter_001,2026-07-02 12:00:00,44.803673,-29.548657,20.299082,0.900000,120.000000
37,drifter_001,2026-07-02 13:00:00,44.800864,-29.538159,20.196256,0.825460,112.235429
38,drifter_001,2026-07-02 14:00:00,44.799104,-29.528544,20.100224,0.756000,105.000000
39,drifter_001,2026-07-02 15:00:00,44.798147,-29.519687,20.017620,0.696353,98.786797
40,drifter_001,2026-07-02 16:00:00,44.797737,-29.511413,19.954156,0.650585,94.019238
41,drifter_001,2026-07-02 17:00:00,44.797637,-29.503505,19.914220,0.621813,91.022225
42,drifter_001,2026-07-02 18:00:00,44.797637,-29.495721,19.900591,0.612000,90.000000
43,drifter_001,2026-07-02 19:00:00,44.797538,-29.487813,19.914245,0.621813,91.022225
44,drifter_001,2026-07-02 20:00:00,44.797128,-29.479538,19.954308,0.650585,94.019238
45,drifter_001,2026-07-02 21:00:00,44.796171,-29.470682,20.018115,0.696353,98.786797
46,drifter_001,2026-07-02 22:00:00,44.794411,-29.461067,20.101397,0.756000,105.000000
47,drifter_001,2026-07-02 23:00:00,44.791602,-29.450568,20.198572,0.825460,112.235429

In [17]:
plt.figure(figsize=(8, 6))
plt.plot(data["lon"], data["lat"], marker="o", linestyle="-")
plt.title("Buoy drifter_001 – latitude/longitude track")
plt.xlabel("Longitude (°)")
plt.ylabel("Latitude (°)")
plt.grid(True)
plt.tight_layout()
plt.savefig("buoy_track.png")  # saved in the current working directory
plt.close()

In [5]:
do_spike_check(
    value=data.sst,
    lat=data.lat,
    lon=data.lon,
    date=data.date,
    max_gradient_space=0.5,
    max_gradient_time=1.0,
    delta_t=1.0,
    n_neighbours=5,
)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
dtype: int64

In [6]:
do_track_check(
    vsi=data.vsi,
    dsi=data.dsi,
    lat=data.lat,
    lon=data.lon,
    date=data.date,
    max_direction_change=60.0,
    max_speed_change=10.0,
    max_absolute_speed=40.0,
    max_midpoint_discrepancy=150.0,
)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
dtype: int64

In [7]:
do_iquam_track_check(
    lat=data.lat,
    lon=data.lon,
    date=data.date,
    speed_limit=15.0,
    delta_d=1.11,
    delta_t=0.01,
    n_neighbours=5,
)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
dtype: int64

In [8]:
qc_dict = {
    "spike_check": {
        "func": "do_spike_check",
        "names": {
            "value": "sst",
            "lat": "lat",
            "lon": "lon",
            "date": "date",
        },
        "arguments": {
            "max_gradient_space": 0.5,
            "max_gradient_time": 1.0,
            "delta_t": 1.0,
            "n_neighbours": 5,
        },
    },
    "track_check": {
        "func": "do_track_check",
        "names": {
            "vsi": "vsi",
            "dsi": "dsi",
            "lat": "lat",
            "lon": "lon",
            "date": "date",
        },
        "arguments": {
            "max_direction_change": 60.0,
            "max_speed_change": 10.0,
            "max_absolute_speed": 40.0,
            "max_midpoint_discrepancy": 150.0,
        },
    },
    "iquam_track_check": {
        "func": "do_iquam_track_check",
        "names": {
            "lat": "lat",
            "lon": "lon",
            "date": "date",
        },
        "arguments": {
            "speed_limit": 15.0,
            "delta_d": 1.11,
            "delta_t": 0.01,
            "n_neighbours": 5,
        },
    },
}
do_multiple_sequential_check(
    data,
    qc_dict=qc_dict,
    groupby="buoy_id",
)

    spike_check  track_check  iquam_track_check
0             0            0                  0
1             0            0                  0
2             0            0                  0
3             0            0                  0
4             0            0                  0
5             0            0                  0
6             0            0                  0
7             0            0                  0
8             0            0                  0
9             0            0                  0
10            0            0                  0
11            0            0                  0
12            0            0                  0
13            0            0                  0
14            0            0                  0
15            0            0                  0
16            0            0                  0
17            0            0                  0
18            0            0                  0
19            0            0                  0
20            0            0                  0
21            0            0                  0
22            0            0                  0
23            0            0                  0
24            0            0                  0
25            0            0                  0
26            0            0                  0
27            0            0                  0
28            0            0                  0
29            0            0                  0
30            0            0                  0
31            0            0                  0
32            0            0                  0
33            0            0                  0
34            0            0                  0
35            0            0                  0
36            0            0                  0
37            0            0                  0
38            0            0                  0
39            0            0                  0
40            0            0                  0
41            0            0                  0
42            0            0                  0
43            0            0                  0
44            0            0                  0
45            0            0                  0
46            0            0                  0
47            0            0                  0